// Products data for accessibility e-commerce demo
export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    description: "Comfortable over-ear headphones with noise cancellation.",
    image: "/headphone.jpeg",
    alt: "Black wireless over-ear headphones",
    price: "Rs 500",
    category: "hearing",
    priceValue: 500,
  },
  {
    id: 2,
    name: "Braille Keyboard",
    description: "Keyboard with Braille for visually impaired users.",
    image: "/brailkeyboard.jpeg",
    alt: "Braille keyboard with raised dots on keys",
    price: "Rs 45000",
    category: "vision",
    priceValue: 45000,
  },
  {
    id: 3,
    name: "Wheelchair",
    description: "Lightweight, foldable wheelchair for easy mobility.",
    image: "/wheelchair.jpeg",
    alt: "Lightweight foldable wheelchair",
    price: "Rs 2500",
    category: "mobility",
    priceValue: 2500,
  },
  {
    id: 4,
    name: "Smart Cane (Obstacle Detector)",
    description: "Uses sensors to detect obstacles and provides alerts via vibrations.",
    image: "/ObstacleDetector.jpeg",
    alt: "Smart cane with obstacle detection sensors",
    price: "Rs 3000",
    category: "vision",
    priceValue: 3000,
  },
  {
    id: 5,
    name: "Behind-The-Ear (BTE) Digital Hearing Aid",
    description: "An entry-level hearing aid that is powerful and durable.",
    image: "/behind_the_ear.jpeg",
    alt: "Behind-the-ear digital hearing aid",
    price: "Rs 8000",
    category: "hearing",
    priceValue: 8000,
  },
  {
    id: 6,
    name: "Sensory Toy Kit for Autism/ADHD",
    description: "A kit of sensory toys designed for children with Autism or ADHD.",
    image: "/SensoryToyKitforAutism.jpeg",
    alt: "Sensory toy kit for Autism and ADHD",
    price: "Rs 1500",
    category: "sensory",
    priceValue: 1500,
  },
  {
    id: 7,
    name: "Vibrating Alarm Clock",
    description:
      "An alarm clock designed for deaf or hard-of-hearing individuals that uses vibrations to wake them up.",
    image: "/alarmClock.jpeg",
    alt: "Vibrating alarm clock for deaf or hard-of-hearing",
    price: "Rs 2000",
    category: "hearing",
    priceValue: 2000,
  },
  {
    id: 8,
    name: "Orthopedic Shoes (Diabetic-friendly)",
    description:
      "Footwear designed to protect and comfort sensitive feet, with non-binding, soft soles.",
    image: "/shoes.jpeg",
    alt: "Pair of orthopedic diabetic-friendly shoes",
    price: "Rs 1000",
    category: "mobility",
    priceValue: 1000,
  },
];

